### PR TITLE
Added support for more props in the smart component, with docs and examples

### PR DESCRIPTION
**Pull request by wesleytodd**
Added a docs section to the readme for the props, and made sure they all work with the top level managed component.

### CODE REVIEW

**Review by djake — APPROVED** [review]

**Comment by wesleytodd** [comment]
@djake Question, I said that the `store` prop requires a `@streammedev/flux-store`, but I think it would work with a redux store, can you tell me if that is correct?

**Comment by djake** [comment]
@wesleytodd  yep, I think so

**Comment by wesleytodd** [comment]
Wrong wes :)

Sorry for the mention wes

**Comment by wesleytodd** [comment]
Published as `@streammedev/hermes@1.4.0`

**Pull request merged**
